forum/urls.py
from django.urls import path
from forum.views import ForumIndexView, SecaoView, SubsecaoView, TopicoView, TopicoCreateView, PostCreateView
from forum.views import TopicoCreateApiView, CurtidaPostApiView

from rest_framework.routers import DefaultRouter

app_name= 'forum'

urlpatterns = [
    path('', ForumIndexView.as_view(), name="index-Forum"),
    path('secao/<int:pk>/', SecaoView.as_view(), name="secaoView"),
    path('subsecao/<int:pk>/', SubsecaoView.as_view(), name="subsecaoView"),
    path('topico/<int:pk>/', TopicoView.as_view(), name="topicoView"),
    path('topico/<int:pk>/criarPost', PostCreateView.as_view(), name="postCreateView"),
    path('novo-topico/<int:pkSecao>', TopicoCreateView.as_view(), name="topico-create-view"),
    path('novo-topico/<int:pkSecao>/<int:pkSubsecao>/', TopicoCreateView.as_view(), name="topico-create-view2")


    
]

router = DefaultRouter(trailing_slash=False)
router.register(r'api/Topico_Create',TopicoCreateApiView, basename='TopicoApi')
router.register(r'api/PostLike',CurtidaPostApiView, basename='CurtidaApi')


urlpatterns += router.urls

forum/models/Area.py
from django.db import models

# Create your models here.
class Area(models.Model):
    id = models.BigAutoField(primary_key=True)

    nome = models.CharField(u'Nome da Área', max_length=255)
    descricao = models.TextField(u'Descrição da Área', max_length=500, null=True, blank=True)
    
    ativo = models.BooleanField(verbose_name=u'Ativo?', default=True, editable=True)

    class Meta:
        verbose_name = "Área"
        verbose_name_plural = "Áreas"

    def __str__(self):
        return self.nome

forum/models/CurtidaPost.py
from django.db import models

from forum.models import Post
from cadastro.models import Perfil

class CurtidaPost(models.Model):
    id = models.BigAutoField(primary_key=True)

    post = models.ForeignKey(Post, verbose_name=u'Post', on_delete=models.CASCADE)

    quemCurtiu = models.ForeignKey(Perfil, verbose_name='Perfil', on_delete=models.CASCADE)
    
    dataCadastro = models.DateTimeField('Data de Cadastro', auto_now_add=True, null=True)

    ativo = models.BooleanField(verbose_name=u'Ativo?', default=True, editable=True)

    class Meta:
        verbose_name = "Curtida Post"
        verbose_name_plural = "Curtidas Posts"

    def __str__(self):
        return self.quemCurtiu

forum/models/Post.py
from collections.abc import Iterable
from django.db import models
from django.apps import apps

from forum.models import Topico
from cadastro.models import Perfil
from desafios.models import TipoTutorial
# Create your models here.
class Post(models.Model):
    id = models.BigAutoField(primary_key=True)

    topico = models.ForeignKey(Topico, verbose_name=("topico"), on_delete=models.CASCADE)
    
    quemPostou = models.ForeignKey(Perfil, verbose_name=('perfil'), on_delete=models.CASCADE)

    conteudo = models.TextField(u'Conteúdo do Post', max_length=500000)

    index = models.BooleanField(verbose_name=u'É o Primeiro Post?', default=False, editable=True)
    
    dataCadastro = models.DateTimeField('Data de Cadastro', auto_now_add=True, null=True)

    ativo = models.BooleanField(verbose_name=u'Ativo?', default=True, editable=True)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return f'{self.id} {self.topico} {self.quemPostou}'
    
    def save(self):        
        secao = self.topico.secao

        if secao.area.nome == 'Tutoriais' and self.index:

            Tutorial = apps.get_model('desafios.Tutorial')

            novo_item = Tutorial()
            novo_item.titulo = self.topico.nome
            novo_item.assunto = self.conteudo
            novo_item.tipo = TipoTutorial.objects.get(titulo=secao)
            novo_item.nivel = 1
            novo_item.quemCadastrou = self.quemPostou

        return super().save()

forum/models/RespostaPost.py
from django.db import models

from forum.models import Post

class RespostaPost(models.Model):
    id = models.BigAutoField(primary_key=True)

    post = models.ForeignKey(Post, verbose_name=u'Post', related_name='post', on_delete=models.CASCADE)
    resposta = models.ForeignKey(Post, verbose_name=u'Resposta', related_name='resposta', on_delete=models.CASCADE)
    
    dataCadastro = models.DateTimeField('Data de Cadastro', auto_now_add=True, null=True)

    ativo = models.BooleanField(verbose_name=u'Ativo?', default=True, editable=True)

    class Meta:
        verbose_name = "Resposta Post"
        verbose_name_plural = "Respostas Posts"

    def __str__(self):
        return f'{self.id}'

forum/models/Secao.py
from django.db import models

from forum.models import Area
# Create your models here.
class Secao(models.Model):
    id = models.BigAutoField(primary_key=True)

    nome = models.CharField(u'Nome da Seção', max_length=255)
    descricao = models.TextField(u'Descrição da Seção', max_length=500, null=True, blank=True)
    
    area = models.ForeignKey(Area, verbose_name=("Area"), on_delete=models.CASCADE)

    ativo = models.BooleanField(verbose_name=u'Ativo?', default=True, editable=True)

    class Meta:
        verbose_name = "Seção"
        verbose_name_plural = "Seções"

    def __str__(self):
        return self.nome

forum/models/SubSecao.py
from django.db import models

from forum.models import Secao
# Create your models here.
class SubSecao(models.Model):
    id = models.BigAutoField(primary_key=True)

    nome = models.CharField(u'Nome da Subseção', max_length=255)
    descricao = models.TextField(u'Descrição da Subseção', max_length=500, null=True, blank=True)
    
    secao = models.ForeignKey(Secao, verbose_name=("secao"), on_delete=models.CASCADE)

    ativo = models.BooleanField(verbose_name=u'Ativo?', default=True, editable=True)

    class Meta:
        verbose_name = "Subseção"
        verbose_name_plural = "Subseções"

    def __str__(self):
        return self.nome

forum/models/Topico.py
from django.db import models

from forum.models import Secao, SubSecao
# Create your models here.
class Topico(models.Model):
    id = models.BigAutoField(primary_key=True)

    nome = models.CharField(u'Nome da Tópico', max_length=255)
    
    secao = models.ForeignKey(Secao, verbose_name=("secao"), on_delete=models.CASCADE)
    subsecao = models.ForeignKey(SubSecao, verbose_name=("subsecao"), null=True, blank=True, on_delete=models.CASCADE)
    
    dataCadastro = models.DateTimeField('Data de Cadastro', auto_now_add=True, null=True)

    ativo = models.BooleanField(verbose_name=u'Ativo?', default=True, editable=True)

    class Meta:
        verbose_name = "Tópico"
        verbose_name_plural = "Tópicos"

    def __str__(self):
        return self.nome

forum/forms/PostForm.py
from django.forms import ModelForm
from django import forms

from forum.models import Post

class PostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False

    class Meta:
        model = Post
        fields = '__all__'

forum/views/ForumIndexView.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from forum.models import Area, Post, Secao, SubSecao,Topico

class ForumIndexView(LoginRequiredMixin,TemplateView):
    template_name="ForumIndex.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        areas = Area.objects.all()

        for area in areas:
            
            secoes = Secao.objects.filter(area=area)

            if secoes:
                for secao in secoes:
                    secao.posts = 0
                    topicos = Topico.objects.filter(secao=secao)
                    
                    for topico in topicos:
                        posts = Post.objects.filter(topico=topico)

                        if posts:
                            secao.posts += posts.count()

                    if topicos:
                        secao.topicos = topicos

                    subsecoes = SubSecao.objects.filter(secao=secao)
                    secao.subsecoes = subsecoes
                    secao.ultimoPost = Post.objects.filter(topico__secao=secao).last()

            area.secoes = secoes
        
        context['areas'] = areas
        return self.render_to_response(context)

forum/views/PostCreateView.py
from django.conf import settings
from django.views.generic.edit import UpdateView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
##########
from forum.models import Topico, Post,RespostaPost
from forum.forms import PostForm

class PostCreateView(UpdateView):
    form_class = PostForm
    model = Post
    mensagemSucesso = 'Post criado com sucesso'
    mensagemError = 'Não foi possível criar o post'

    def post(self, request, *args, **kwargs):
        # print(f'Request: {request.POST}')
        form = self.get_form()
        # print(f'Form: {form}')

        if form.is_valid():
            post = form.save(commit=False)
            post.id = None
            post.ativo = True
                
            post.save()
            if request.POST.get('respondendo'):
                resposta = RespostaPost()
                resposta.post = Post.objects.get(id=request.POST.get('respondendo'))
                resposta.resposta = post
                resposta.ativo = True
                resposta.save()
            

            messages.success(self.request, self.mensagemSucesso)
            return HttpResponseRedirect(reverse('forum:topicoView',  kwargs={'pk': post.topico.id}))
        else:
            return self.form_invalid(form)
        

forum/views/SecaoView.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from forum.models import Post, Secao, SubSecao,Topico

class SecaoView(LoginRequiredMixin,TemplateView):
    template_name="Secao.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        secao = Secao.objects.get(id=kwargs.get('pk'))

        topicos = Topico.objects.filter(secao=secao,subsecao=None)
                    
        for topico in topicos:

            posts = Post.objects.filter(topico=topico)
            topico.indexPost = Post.objects.get(topico=topico,index=True,ativo=True)
            topico.posts = posts
            topico.ultimoPost = posts.last()
            
            if posts:
                secao.posts = posts

        if topicos:
            secao.topicos = topicos

        subsecoes = SubSecao.objects.filter(secao=secao)

        for subsecao in subsecoes:
            topicos2 = Topico.objects.filter(subsecao=subsecao)
            subsecao.topicos = topicos2

            for topico in topicos2:
                posts = Post.objects.filter(topico=topico)

                if posts:
                    subsecao.posts = posts
            subsecao.ultimoPost = Post.objects.filter(topico__subsecao=subsecao).last()

        secao.subsecoes = subsecoes

        secao.ultimoPost = Post.objects.filter(topico__secao=secao).last()

        context['secao'] = secao

        return self.render_to_response(context)

forum/views/SubsecaoView.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from forum.models import Post, Secao, SubSecao,Topico

class SubsecaoView(LoginRequiredMixin, TemplateView):
    template_name="Subsecao.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        subsecao = SubSecao.objects.get(id=kwargs.get('pk'))

        topicos = Topico.objects.filter(subsecao=subsecao)
                    
        for topico in topicos:

            posts = Post.objects.filter(topico=topico)
            topico.indexPost = Post.objects.get(topico=topico,index=True,ativo=True)
            topico.posts = posts
            topico.ultimoPost = posts.last()
            
            if posts:
                subsecao.posts = posts

        if topicos:
            subsecao.topicos = topicos

        context['secao'] = subsecao.secao

        context['subsecao'] = subsecao

        return self.render_to_response(context)

forum/views/TopicoCreateView.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from forum.models import Post, Secao, SubSecao,Topico
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField


class TopicoCreateView(LoginRequiredMixin,TemplateView):
    template_name="TopicoCreate.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        secao = kwargs.get('pkSecao')

        secaoObj = Secao.objects.get(id=secao)

        subsecao = kwargs.get('pkSubsecao')

        subSecaoObj = SubSecao.objects.get(id=subsecao) if subsecao else None

        context["post"] = SummernoteTextField()

        context["secao"] = secaoObj
        context["subSecao"] = subSecaoObj 

        # print(f'Secao: {secao} e Subsecao: {subsecao}')
        
        return context

forum/views/TopicoView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView

from cadastro.models import Perfil
from forum.models import Topico, Post, RespostaPost
from forum.forms import PostForm
class TopicoView(LoginRequiredMixin, DetailView):
    model = Topico
    template_name = "Topico.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        self.object = self.get_object()

        posts = Post.objects.filter(topico=self.object,ativo=True).order_by('-index','dataCadastro')
        for post in posts:
            post.curtido = post.curtidapost_set.filter(quemCurtiu__pessoa__user=self.request.user,ativo=True).exists()
            post.curtidas = post.curtidapost_set.filter(ativo=True)
            
            if post.resposta.filter(resposta=post, ativo=True).exists():
                post.respondendo = RespostaPost.objects.get(resposta=post)

        context['topico'] = self.object
        context['pessoaPerfil'] = Perfil.objects.get(pessoa__user=self.request.user)
        context['form'] = PostForm()
        context['posts'] = posts

        # print(f'Context: {context}')

        return context

forum/templates/Topico.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <div class="title-forum">
        
        {% comment %} <p class="text-7xl text-center mt-4 pb-4 font-extrabold text-white text-4xl">Code Junior Fórum</p> {% endcomment %}
    </div>

    <!-- Breadcrumb -->
    <div class="flex w-9/12 justify-start mb-4 px-6">
        <nav class="flex mx-10 px-4 py-3 text-gray-700 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-800 dark:border-gray-700" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-3">
            <li class="inline-flex items-center">
                <a href="{% url "forum:index-Forum"%}" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400 dark:hover:text-white">
                <svg class="w-3 h-3 mr-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
                </svg>
                <a href="{% url "forum:index-Forum"%}">
                    Fórum
                </a>
            </li>
            <li>
                <div class="flex items-center">
                <svg class="w-3 h-3 mx-1 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                </svg>
                <a href="#" class="ml-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ml-2 dark:text-gray-400 dark:hover:text-white">
                    {% if topico.subsecao %}
                        <a href="{% url "forum:subsecaoView" pk=topico.subsecao.id%}">
                            {{topico.subsecao}}
                        </a>
                    {% else %}
                        <a href="{% url "forum:secaoView" pk=topico.secao.id%}">
                            {{topico.secao}}
                        </a>
                    {% endif %}
                </a>
                </div>
            </li>
            <li aria-current="page">
                <div class="flex items-center">
                <svg class="w-3 h-3 mx-1 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                </svg>
                <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">{{topico}}</span>
                </div>
            </li>
            </ol>
        </nav>
    </div>
    
  
    <div class="areas pb-6">
        {% csrf_token %}
        <input type="hidden" name="urlApiCurtida" id="urlApiCurtida" value="/codejunior/forum/api/PostLike">
        <div class="area mb-4">
            <div class="area-header">
                <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                    <table class="w-full text-sm text-left text-sky-600">
                        <thead class="text-xs text-white uppercase bg-blue-600 border-b border-blue-400 ">
                            <div class="p-4 mb-2 bg-sky-500	text-white rounded-lg">
                                {{topico}}
                            </div>
                        </thead>
                        <tbody>
                            {% for post in posts %}
                                <tr class="bg-slate-200 rounded-lg border-b border-blue-400 pb-4">
                                    <th class="px-1 py-4 w-1/6 font-medium text-sky-600 align-top">
                                        <div class="perfil  flex-col grid justify-items-center">
                                            <span class="text-green-700 font-bold text-lg">
                                                {{post.quemPostou}}
                                            </span>

                                            <img class="img-perfil rounded-lg drop-shadow-xl shadow-inner" width="150px" src="{{post.quemPostou.imagem.url}}" alt="">

                                            <span class="text-slate-700 font-regular text-sm">
                                                Postagens: {{post.quemPostou.retornaPosts}}
                                            </span>
                                        </div>

                                    </th>
                                        
                                    
                                    <th class="grid gap-y-32 grid-cols-1 w-auto px-1 pt-6 text-slate-700" style="border-left: 1px solid #cfcfcf;">
                                        <div>
                                            <div class="flex justify-end mr-4 divide-x divide-blue-200">
                                                <button id="btn-like-{{post.id}}" class="btn-like flex items-center bg-teal-600 p-1 text-slate-100 rounded-l-lg" data-curtido="false" data-post="{{post.id}}">
                                                    {% if not post.curtido%}
                                                        <svg class="w-3 h-3 mr-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 21 20">
                                                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m11.479 1.712 2.367 4.8a.532.532 0 0 0 .4.292l5.294.769a.534.534 0 0 1 .3.91l-3.83 3.735a.534.534 0 0 0-.154.473l.9 5.272a.535.535 0 0 1-.775.563l-4.734-2.49a.536.536 0 0 0-.5 0l-4.73 2.487a.534.534 0 0 1-.775-.563l.9-5.272a.534.534 0 0 0-.154-.473L2.158 8.48a.534.534 0 0 1 .3-.911l5.294-.77a.532.532 0 0 0 .4-.292l2.367-4.8a.534.534 0 0 1 .96.004Z"/>
                                                        </svg>
                                                        Curtir
                                                    {% else %}
                                                        <svg class="w-3 h-3 mr-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20">
                                                            <path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"/>
                                                        </svg>
                                                        Curtido
                                                    {% endif %}
                                                </button>

                                                <button class="btn-reply bg-cyan-600 p-1 flex items-center text-slate-100 rounded-r-lg" data-post="{{post.id}}">
                                                    <svg class="w-3 h-3 mr-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 19 17">
                                                        <path d="M2.057 6.9a8.718 8.718 0 0 1 6.41-3.62v-1.2A2.064 2.064 0 0 1 9.626.2a1.979 1.979 0 0 1 2.1.23l5.481 4.308a2.107 2.107 0 0 1 0 3.3l-5.479 4.308a1.977 1.977 0 0 1-2.1.228 2.063 2.063 0 0 1-1.158-1.876v-.942c-5.32 1.284-6.2 5.25-6.238 5.44a1 1 0 0 1-.921.807h-.06a1 1 0 0 1-.953-.7A10.24 10.24 0 0 1 2.057 6.9Z"/>
                                                    </svg>
                                                    Responder
                                                </button>
                                            </div>
                                            <div id="post-{{post.id}}">
                                                {% if post.respondendo %}
                                                <span class="text-green-700 italic font-bold text-sm">
                                                    Respondendo a:
                                                </span>
                                                    <p class="text-sm italic text-gray-400 mb-2 border-2 bg-slate-100 border-b-slate-400" id="postRespondendo">
                                                        {{post.respondendo.post.conteudo|safe|truncatechars:100}}
                                                    </p>
                                                {% endif %}
                                                {{post.conteudo|safe}}
                                            </div>
                                        </div>
                                        <div>
                                            <span>Curtido por:</span>
                                            <div id="like-{{post.id}}" class="border-2 py-2 mb-1 border-y-cyan-500">
                                                {% for curtida in post.curtidas %}
                                                    <span>
                                                        {% if forloop.counter0 > 0 %}
                                                        ,
                                                        {% endif %}
                                                        {{curtida.quemCurtiu.nome}}
                                                    </span>
                                                {% endfor %}
                                            </div>
                                        </div>

                                    </th>
                                </tr>
                                
                            {% endfor %}

                        </tbody>
                    </table>
                </div>

                <div class="resposta pt-3 shadow-md">
                    <div class="card bg-slate-100 p-4 sm:rounded-lg">
                        <div class="">
                            <input type="hidden" name="urlApiTopico" id="urlApiTopico" value="/codejunior/forum/api/Topico_Create">
                            <input type="hidden" name="secao" id="secaoId" value="{{secao.id}}">
                            <input type="hidden" name="subsecao" id="subsecaoId" value="{{subsecao.id}}">

                        </div>
                        <div id="respondendoDiv" class="hidden pb-4"> 
                            <div class="w-100 flex justify-end pr-3">
                                <button id="removeReply">
                                    <svg class="w-[12px] h-[12px] text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                                      </svg>
                                </button>
                            </div>
                            <span class="text-green-700 font-bold text-sm">
                                Respondendo:
                            </span>
                            <p class="text-sm text-gray-400" id="postRespondendo">

                            </p>
                        </div>

                        <form action="{% url "forum:postCreateView" topico.id %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="hidden" name="topico" id="id_topico" value="{{topico.id}}">
                            <input type="hidden" name="quemPostou" id="id_quemPostou" value="{{pessoaPerfil.id}}">
                            <input type="hidden" name="respondendo" id="id_respondendo" value="">

                            
                            <div class="w-full mb-4 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-700 dark:border-gray-600">
                                <div class="px-4 py-2 bg-white rounded-b-lg dark:bg-gray-800">
                                    <label for="editor" class="sr-only">Publicar post</label>
                                    <textarea name="conteudo" id="id_conteudo" rows="8" class="block w-full px-0 text-sm text-gray-800 bg-white border-0 dark:bg-gray-800 focus:ring-0 dark:text-white dark:placeholder-gray-400" placeholder="Escreva sua resposta..." required></textarea>
                                </div>
                            </div>
                            <div class="w-100 flex justify-end">
                                <input type="submit" id="btn-criar-topico" value="Responder" class="inline-flex items-center px-5 py-2.5 text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-blue-200 hover:bg-blue-800">
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="{% static "js/apiCurtirPost.js" %}"></script>
    <script src="{% static "js/apiResponderPost.js" %}"></script>
{% endblock content %}

forum/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppins:wght@100;300;400;700&family=Roboto+Slab:wght@100&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/forumIndex.css" %}">
  <script src="https://cdn.tailwindcss.com"></script>

  <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  {% block static_css %}{% endblock static_css %}

  <title>
    {% block title %}CodeJunior | Fórum{% endblock title %}
  </title>
</head>
<body>
  <header class="flex justify-center items-center font-instrument-sans p-20" style="background-color: #3586FF;">
    <a class="title-forum pr-4" href="{% url "forum:index-Forum" %}">
        
        <span class="text-7xl text-center mt-4 pb-4 font-extrabold text-white text-4xl">Code Junior Fórum</span>
 
    </a>

    <a href="{% url "desafios-index" %}" class="text-white text-2xl mx-4">
      Portal
    </a>
    <a href="{% url "desafios-list" %}" class="text-white text-2xl mx-4">
      Trilhas
    </a>
    
    <a href="{% url "biliotecaList" %}" class="text-white text-2xl mx-4">
      Biblioteca
    </a>
      
  </header>

  <main class="main-content">
    {% block content %}{% endblock content %}
  </main>

  <section>
    <div class='air air1'></div>
    <div class='air air2'></div>
    <div class='air air3'></div>
    <div class='air air4'></div>
  </section>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="//unpkg.com/ace-builds/src-min-noconflict/ace.js"></script>

  {% block static_js %}{% endblock static_js %}

</body>
</html>